export const prizeColumns = [
  { key: "firstPrize", label: "1st Prize" },
  { key: "secondPrize", label: "2nd Prize" },
  { key: "thirdPrize", label: "3rd Prize" },
  { key: "grossPrize", label: "Gross Prize" },
  { key: "nearestToPin", label: "Nearest to Pin" },
  { key: "nearestToPinInTwo", label: "Nearest to Pin in 2" },
  { key: "longestDrive", label: "Longest Drive" },
  { key: "twosMoney", label: "2's Money" },
  { key: "numptyPrize", label: "Numpty Prize" },
] as const;

export type PrizeColumnKey = (typeof prizeColumns)[number]["key"];

export type MemberRow = {
  name: string;
  handicap: number | string;
} & Record<PrizeColumnKey, number>;

export const members: MemberRow[] = [
  {
    name: "R Ryan",
    handicap: 0.4,
    firstPrize: 0,
    secondPrize: 0,
    thirdPrize: 0,
    grossPrize: 0,
    nearestToPin: 0,
    nearestToPinInTwo: 0,
    longestDrive: 0,
    twosMoney: 0,
    numptyPrize: 0,
  },
  {
    name: "Chris Bramley",
    handicap: 0.8,
    firstPrize: 0,
    secondPrize: 0,
    thirdPrize: 0,
    grossPrize: 0,
    nearestToPin: 0,
    nearestToPinInTwo: 0,
    longestDrive: 0,
    twosMoney: 0,
    numptyPrize: 0,
  },
  {
    name: "Jonny",
    handicap: 1.0,
    firstPrize: 0,
    secondPrize: 0,
    thirdPrize: 0,
    grossPrize: 0,
    nearestToPin: 0,
    nearestToPinInTwo: 0,
    longestDrive: 0,
    twosMoney: 0,
    numptyPrize: 0,
  },
  {
    name: "Gregg",
    handicap: 5.0,
    firstPrize: 0,
    secondPrize: 0,
    thirdPrize: 0,
    grossPrize: 0,
    nearestToPin: 0,
    nearestToPinInTwo: 0,
    longestDrive: 0,
    twosMoney: 0,
    numptyPrize: 0,
  },
  {
    name: "David",
    handicap: 6.7,
    firstPrize: 0,
    secondPrize: 0,
    thirdPrize: 0,
    grossPrize: 0,
    nearestToPin: 0,
    nearestToPinInTwo: 0,
    longestDrive: 0,
    twosMoney: 0,
    numptyPrize: 0,
  },
  {
    name: "Callum",
    handicap: 10.3,
    firstPrize: 0,
    secondPrize: 0,
    thirdPrize: 0,
    grossPrize: 0,
    nearestToPin: 0,
    nearestToPinInTwo: 0,
    longestDrive: 0,
    twosMoney: 0,
    numptyPrize: 0,
  },
  {
    name: "Jk",
    handicap: 11.0,
    firstPrize: 0,
    secondPrize: 0,
    thirdPrize: 0,
    grossPrize: 0,
    nearestToPin: 0,
    nearestToPinInTwo: 0,
    longestDrive: 0,
    twosMoney: 0,
    numptyPrize: 0,
  },
  {
    name: "R Colin",
    handicap: 12.0,
    firstPrize: 0,
    secondPrize: 0,
    thirdPrize: 0,
    grossPrize: 0,
    nearestToPin: 0,
    nearestToPinInTwo: 0,
    longestDrive: 0,
    twosMoney: 0,
    numptyPrize: 0,
  },
  {
    name: "Stuart",
    handicap: 12.5,
    firstPrize: 0,
    secondPrize: 0,
    thirdPrize: 0,
    grossPrize: 0,
    nearestToPin: 0,
    nearestToPinInTwo: 0,
    longestDrive: 0,
    twosMoney: 0,
    numptyPrize: 0,
  },
  {
    name: "Ray",
    handicap: 13.0,
    firstPrize: 0,
    secondPrize: 0,
    thirdPrize: 0,
    grossPrize: 0,
    nearestToPin: 0,
    nearestToPinInTwo: 0,
    longestDrive: 0,
    twosMoney: 0,
    numptyPrize: 0,
  },
  {
    name: "Aidy",
    handicap: 14.2,
    firstPrize: 0,
    secondPrize: 0,
    thirdPrize: 0,
    grossPrize: 0,
    nearestToPin: 0,
    nearestToPinInTwo: 0,
    longestDrive: 0,
    twosMoney: 0,
    numptyPrize: 0,
  },
  {
    name: "Dougie",
    handicap: 14.3,
    firstPrize: 0,
    secondPrize: 0,
    thirdPrize: 0,
    grossPrize: 0,
    nearestToPin: 0,
    nearestToPinInTwo: 0,
    longestDrive: 0,
    twosMoney: 0,
    numptyPrize: 0,
  },
  {
    name: "S Nixon",
    handicap: 15.2,
    firstPrize: 0,
    secondPrize: 0,
    thirdPrize: 0,
    grossPrize: 0,
    nearestToPin: 0,
    nearestToPinInTwo: 0,
    longestDrive: 0,
    twosMoney: 0,
    numptyPrize: 0,
  },
  {
    name: "P Nixon",
    handicap: 17.6,
    firstPrize: 0,
    secondPrize: 0,
    thirdPrize: 0,
    grossPrize: 0,
    nearestToPin: 0,
    nearestToPinInTwo: 0,
    longestDrive: 0,
    twosMoney: 0,
    numptyPrize: 0,
  },
  {
    name: "Sheamie",
    handicap: 17.9,
    firstPrize: 0,
    secondPrize: 0,
    thirdPrize: 0,
    grossPrize: 0,
    nearestToPin: 0,
    nearestToPinInTwo: 0,
    longestDrive: 0,
    twosMoney: 0,
    numptyPrize: 0,
  },
  {
    name: "Tim",
    handicap: 19.8,
    firstPrize: 0,
    secondPrize: 0,
    thirdPrize: 0,
    grossPrize: 0,
    nearestToPin: 0,
    nearestToPinInTwo: 0,
    longestDrive: 0,
    twosMoney: 0,
    numptyPrize: 0,
  },
  {
    name: "James Ferris",
    handicap: 20.0,
    firstPrize: 0,
    secondPrize: 0,
    thirdPrize: 0,
    grossPrize: 0,
    nearestToPin: 0,
    nearestToPinInTwo: 0,
    longestDrive: 0,
    twosMoney: 0,
    numptyPrize: 0,
  },
  {
    name: "Marcus",
    handicap: 20.0,
    firstPrize: 0,
    secondPrize: 0,
    thirdPrize: 0,
    grossPrize: 0,
    nearestToPin: 0,
    nearestToPinInTwo: 0,
    longestDrive: 0,
    twosMoney: 0,
    numptyPrize: 0,
  },
  {
    name: "R Jeff",
    handicap: 21.7,
    firstPrize: 0,
    secondPrize: 0,
    thirdPrize: 0,
    grossPrize: 0,
    nearestToPin: 0,
    nearestToPinInTwo: 0,
    longestDrive: 0,
    twosMoney: 0,
    numptyPrize: 0,
  },
  {
    name: "Scotty",
    handicap: 21.8,
    firstPrize: 0,
    secondPrize: 0,
    thirdPrize: 0,
    grossPrize: 0,
    nearestToPin: 0,
    nearestToPinInTwo: 0,
    longestDrive: 0,
    twosMoney: 0,
    numptyPrize: 0,
  },
  {
    name: "R Derek",
    handicap: 22.6,
    firstPrize: 0,
    secondPrize: 0,
    thirdPrize: 0,
    grossPrize: 0,
    nearestToPin: 0,
    nearestToPinInTwo: 0,
    longestDrive: 0,
    twosMoney: 0,
    numptyPrize: 0,
  },
  {
    name: "James Lynn",
    handicap: 22.7,
    firstPrize: 0,
    secondPrize: 0,
    thirdPrize: 0,
    grossPrize: 0,
    nearestToPin: 0,
    nearestToPinInTwo: 0,
    longestDrive: 0,
    twosMoney: 0,
    numptyPrize: 0,
  },
  {
    name: "Stevie Paine",
    handicap: 23.5,
    firstPrize: 0,
    secondPrize: 0,
    thirdPrize: 0,
    grossPrize: 0,
    nearestToPin: 0,
    nearestToPinInTwo: 0,
    longestDrive: 0,
    twosMoney: 0,
    numptyPrize: 0,
  },
  {
    name: "Quinzo",
    handicap: 24.8,
    firstPrize: 0,
    secondPrize: 0,
    thirdPrize: 0,
    grossPrize: 0,
    nearestToPin: 0,
    nearestToPinInTwo: 0,
    longestDrive: 0,
    twosMoney: 0,
    numptyPrize: 0,
  },
  {
    name: "Connor",
    handicap: 26.0,
    firstPrize: 0,
    secondPrize: 0,
    thirdPrize: 0,
    grossPrize: 0,
    nearestToPin: 0,
    nearestToPinInTwo: 0,
    longestDrive: 0,
    twosMoney: 0,
    numptyPrize: 0,
  },
  {
    name: "R Scott",
    handicap: 28.0,
    firstPrize: 0,
    secondPrize: 0,
    thirdPrize: 0,
    grossPrize: 0,
    nearestToPin: 0,
    nearestToPinInTwo: 0,
    longestDrive: 0,
    twosMoney: 0,
    numptyPrize: 0,
  },
  {
    name: "Ross",
    handicap: 32.3,
    firstPrize: 0,
    secondPrize: 0,
    thirdPrize: 0,
    grossPrize: 0,
    nearestToPin: 0,
    nearestToPinInTwo: 0,
    longestDrive: 0,
    twosMoney: 0,
    numptyPrize: 0,
  },
  {
    name: "Chris Hall",
    handicap: 36,
    firstPrize: 0,
    secondPrize: 0,
    thirdPrize: 0,
    grossPrize: 0,
    nearestToPin: 0,
    nearestToPinInTwo: 0,
    longestDrive: 0,
    twosMoney: 0,
    numptyPrize: 0,
  },
  {
    name: "Ben",
    handicap: 36,
    firstPrize: 0,
    secondPrize: 0,
    thirdPrize: 0,
    grossPrize: 0,
    nearestToPin: 0,
    nearestToPinInTwo: 0,
    longestDrive: 0,
    twosMoney: 0,
    numptyPrize: 0,
  },
];
